# -*- coding: utf-8 -*-
"""Python-practices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lePioznwHzvxjT5vbxLeYn-EORV48XR9
"""



""" These challenges cover a range of fundamental programming concepts including variables, data types, control structures, functions, and basic data structures.

***Create A folder name Python-challange.
Create 15 files with name hello_world.py for first, add_numbers.py for second, ... and last is overlapping_list.py. Create a new github repo and after completion of of each file push it in github. This will help you navigate and understand git, github, and command line arguments. You can search for hints online if you are stuck. I recommenmd writing input and output as comments before starting any python codes. "HAPPY LEARNING"***
1. **Hello, World!**
   - Write a program that prints "Hello, World!" to the screen.





These challenges are designed to be increasingly complex and help strengthen a beginner's understanding of Python's syntax and basic programming concepts.
"""







# 2**Input and Output**
   #- Write a program that asks the user for their name and greets them with their name.

# 3 Adding Two Numbers

#Write a program that asks the user for two numbers and prints their sum.

# 4 Area of a Circle

#Write a program that asks the user for the radius of a circle and calculates its area. (Use pi from the math module).

# 5 Odd or Even

#Write a program that asks the user to enter a number and prints whether the number is odd or even.

#6 Maximum of Three

#Write a function that takes three numbers as parameters and returns the largest of them.

#7 Sum of a List

#Write a program that creates a list of numbers, then
#calculates and prints the sum of the numbers in the list.

#8 Counting Characters

#Write a program that asks the user to enter a string and then counts and prints
# the number of characters in the string.

"""9 List of Squares

Write a program that asks the user for an integer and prints the list of the squares
 of all integers from 1 to that number.

10 Multiplication Table

Write a program that prints the multiplication table (from 1 to 10) for a number entered by the user.

11 Fibonacci Sequence

Write a program that asks the user how many Fibonacci numbers to generate and then generates them."

12 Palindrome Checker

Write a function that checks whether a passed string is a palindrome or not."

13 List Ends

Write a program that takes a list of numbers and makes a new list of only the first and last elements of the given list.
"

14 Element Search

Write a function that takes an ordered list of numbers and another number, checks whether the number exists in the list and returns (and prints) an appropriate boolean.
"

15 Overlapping Lists

Write a function that takes two lists and returns True if they have at least one common member.
"""